Add group reports for flake-group check (#436)
* `nix flake {info -> metadata}`

* Fix error variant for io errors

* Enable backtrace support for anyhow

* Improve error printing

* Write error report file

* Format workflow file

* Use report file

* Set non-zero exit status if a group fails

* Do not use `local`

* Apply suggestions from review

* Move exit outside the loop

* Fix multi line output

* Fix var substitution

* Different work around for multi lines

diff --git a/.github/workflows/check-flake-files.yml b/.github/workflows/check-flake-files.yml
--- a/.github/workflows/check-flake-files.yml
+++ b/.github/workflows/check-flake-files.yml
@@ -4,11 +4,10 @@ on:
   workflow_dispatch:
   pull_request:
     paths:
-      - 'flakes/**.toml'
+      - "flakes/**.toml"
 
 jobs:
   automatic-custom-flakes-check:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -34,7 +33,30 @@ jobs:
     - name: Try importing all custom flakes
       run: |
         shopt -s globstar
+
+        had_error=0
+
         for flake_group in flakes/**/*.toml
         do
-          ./result/bin/flake-info group "$flake_group" "$(basename "$flake_group" .toml)"
+          echo "::group::Group \"$(basename $flake_group .toml)\""
+        
+         ./result/bin/flake-info group "$flake_group" "$(basename "$flake_group" .toml)" --report
+
+          if [[ -f "./report.txt" ]]
+          then
+            had_error=1
+
+            # sic.:
+            # Workaround for multi line output
+            report="$(< ./report.txt)"
+            report="${report//'%'/'%25'}"
+            report="${report//$'\n'/'%0A'}"
+            report="${report//$'\r'/'%0D'}"
+           
+            echo "::error file=$flake_group::$report"
+          fi
+
+          echo ::endgroup::
+
         done
+        exit $had_error
